### ISSUE TITLE
Error while installing the package

### ISSUE THREAD

**Issue by matteo-mazzanti** [timeflux/timeflux_biosignal#1]
hi!
while trying to install this package, I got an error.
(I previousliy installed timeflux and timeflux_example)

`$ python -m pip install git+https://github.com/timeflux/timeflux_biosignal`  

Collecting git+https://github.com/timeflux/timeflux_biosignal  
  Cloning https://github.com/timeflux/timeflux_biosignal to /tmp/pip-req-build-5l2ce04z  
  Running command git clone -q https://github.com/timeflux/timeflux_biosignal /tmp/pip-req-build-5l2ce04z  
    ERROR: Command errored out with exit status 1:  
     command: /home/mrx/REPO/timeflux_sandbox/timeflux-sandbox/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-5l2ce04z/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-5l2ce04z/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-req-build-5l2ce04z/pip-egg-info  
         cwd: /tmp/pip-req-build-5l2ce04z/  
    Complete output (5 lines):  
    Traceback (most recent call last):  
      File "<string>", line 1, in <module>  
      File "/tmp/pip-req-build-5l2ce04z/setup.py", line 9, in <module>  
        with open('timeflux_example/__init__.py') as f:  
    FileNotFoundError: [Errno 2] No such file or directory: 'timeflux_example/__init__.py'  
    ----------------------------------------  
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by mesca** [comment]
Hi Matteo!
This repo is just a placeholder for now, and does not provide actual functionality. So I am closing this issue while pondering what to do with this repo.
